# Generated by Django 5.0.7 on 2024-07-23 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_color_person_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color', to='App.color'),
        ),
    ]
