# Generated by Django 5.0.7 on 2024-07-24 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_person_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AuthorName', models.CharField(max_length=100, null=True)),
                ('BookName', models.CharField(max_length=300, null=True)),
                ('PublishedDate', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
