# Generated by Django 5.0.7 on 2024-07-25 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='Color',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
